# Generated by Django 5.2.3 on 2025-06-19 04:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(help_text='證券帳號的名稱', max_length=100, verbose_name='申請人帳號名稱')),
                ('phone_number', models.CharField(help_text='聯絡用電話號碼', max_length=20, verbose_name='電話號碼')),
                ('address', models.TextField(help_text='完整的聯絡地址', verbose_name='詳細地址')),
                ('status', models.CharField(choices=[('PENDING', '審核中'), ('APPROVED', '已通過'), ('REJECTED', '已拒絕'), ('ADDITIONAL_REQUIRED', '待補件')], default='PENDING', max_length=20, verbose_name='申請狀態')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='申請時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最後更新時間')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='審核時間')),
                ('rejection_reason', models.TextField(blank=True, help_text='當申請被拒絕時填寫的原因', verbose_name='拒絕原因')),
                ('additional_info_required', models.TextField(blank=True, help_text='需要申請人補充的具體內容和原因', verbose_name='需補充資料說明')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='通過時間')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL, verbose_name='審核人員')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL, verbose_name='申請人')),
            ],
            options={
                'verbose_name': '證券帳號申請',
                'verbose_name_plural': '證券帳號申請',
                'ordering': ['-created_at'],
            },
        ),
    ]
