[project]
name = "securities-application-system"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django>=5.2.3",
]

[dependency-groups]
dev = [
    "coverage>=7.9.1",
]
